### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by TuanTNG** [chqwer2/Multi-view-Self-supervised-Disentanglement-Denoising#1]
Hi, thank you for your awesome work.

Can you release the checkpoints that you used to generate images in your project pages? https://chqwer2.github.io/MeD/

Thank you so much

**Comment by chqwer2** [comment]
Hello, thank you for your interest. We are working to publish these checkpoints as soon as possible. In the meantime, you can easily reproduce the results using the configuration file on the repository. It does not require a large GPU and takes about one day to complete the process.

Best,
Hao
